### ISSUE TITLE
Избавиться от PGArray в возвращаемых типах

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/thirdServer#12]
Сейчас в возвращаемых сервером жсонах можно много где увидеть 
```
      "otherPhotoUrlNews" : {
         "fromPGArray" : [
            " 1 photo",
            " 2 photo"
         ]
      },
```
Выглядит не очень красиво. Можно либо разделить типы на доменные и те которые нужны для базы, а можно заварачивать (или разворачивать) в (из) `PGArray` прямо в инстансах `ToRow` (`FromRow`), которые у тебя и так вручную пишутся, а не дерайвятся

**Comment by Sergey111991KV** [comment]
Избавился
