### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/thirdServer#14]
В процессе работы часто необходимо сделать поиск по проекту и такие ошибки могут усложнить работу тебе и другим :)
https://github.com/Sergey111991KV/thirdServer/blob/master/src/Domain/Services/Auth.hs#L22 - loggin -> login

**Comment by olegromashin** [comment]
https://github.com/Sergey111991KV/thirdServer/blob/master/src/Domain/Services/LogMonad.hs#L41 writFileHandler -> writeFileHandler

**Comment by Sergey111991KV** [comment]
Как сказала бы учительница по русскому - руки бы оторвать) да это проблема конечно, особенно в большом проекте, где на это можно потерять дюжину времени((
