### ISSUE TITLE
Имя LogWrite

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/thirdServer#15]
Непонятное имя у типа данных. Надо переименовать, раз ты там уровни логирования хранишь.

**Comment by ghost** [comment]
Я думаю также стоит вынести параметр уровеня логгирования (Debug, Warn, Error) в конфиг. А то зачем нужна фильтрация которая захардкожена?

**Comment by Sergey111991KV** [comment]
Вынес в конфиг параметры логирования и переименовал непонятное название, а также удалил ненужные функции - излишне параметризированные
