### ISSUE TITLE
mainServer

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/thirdServer#16]
Тело mainServer очень сложно читается из-за вложенных лямбда-функций. Можешь попробовать отрефакторить? Вообще нужно постараться избавиться от такого везде, если где-то есть. То же самое с вложенными друг в друга case-выражениями.

**Comment by Sergey111991KV** [comment]
Можно же оставить не более 2 вложенностей?  эту функцию я подправил, просто много где есть по две проверки - конечно можно их разбить, можно все сделать)) но если проверки простые и функцию нужно писать только для этой одной , которую нужно переписать, то можно не делать?

**Comment by olegromashin** [comment]
Во, так намного лучше и легче читается :+1: 
Вообще лучше стараться везде делать максимум одну вложенность, но если там совсем просто, то не страшно. А если не хочешь много мелких дочерних функций создавать, то можно в блок where выносить. Мы так и делаем, потому что явно видно, что функция только в 1 месте используется.
