### ISSUE TITLE
Описать как запустить проект

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/thirdServer#17]
Из README непонятно чем заполнять строку `postgres "option"`. Надо явно описать, что должно лежать в конфиге.

**Comment by Sergey111991KV** [comment]
Подправил Readme

**Comment by olegromashin** [comment]
Ну смотри, сейчас оно выглядит так:
Replaced:
     "port" with your port for HTTP;
     "postgres" - with your postgres option (host name, port, login and password for database connection),
         it is documentation link postgres-simple  - http://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/Database-PostgreSQL-Simple.html;
     "logConfig" - with your level config (Debug, Warning ,Error);

Переводится так:
Заменено:
   "port" на ваш порт для HTTP;
   ...

Складывается впечатление, что надо заменить слова port, postgresql и logConfig на свои значения, но по итогу надо указать через пробел в ковычках какое значение содержит это поле. Вот это надо описать. Можешь ещё простой пример заполненного конфига в документации привести сразу после этого.

**Comment by olegromashin** [comment]
В иделае ещё в шаблоне указать значения по умолчанию.

**Comment by Sergey111991KV** [comment]
хорошо,  я просто подумал что шаблона достаточно будет, который идет в папке templates
