### ISSUE TITLE
Сокращения имён аргументов

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/thirdServer#18]
Сокращать одну букву в имени не очень корректно.
Например здесь: https://github.com/Sergey111991KV/thirdServer/blob/master/src/Domain/Services/LogMonad.hs#L38
Функция, конечно, короткая и сокращение некритичное, но такие мелкие вещи сразу бросаются в глаза и ухудшают восприятие кода. Если функция была бы длиннее, то пришлось бы постоянно возвращаться к сигнатуре функции и смотреть, что такое `dat` по типу. `date` или `data`? Сокращения не должны вызывать сомнения.

**Comment by olegromashin** [comment]
https://github.com/Sergey111991KV/thirdServer/blob/master/src/Domain/Services/CommonService.hs#L65
Непонятно, что такое idD

**Comment by Sergey111991KV** [comment]
> https://github.com/Sergey111991KV/thirdServer/blob/master/src/Domain/Services/CommonService.hs#L65
> Непонятно, что такое idD

Я хотел для каждой сущности (хочется сказать объекта) хотел сделать что-то типа: type IdDraft = Int или newtype IdDraft = Int.  Но вроде они (сущности), нигде особо не пересекались - кроме, я пока схалтурил и только завернул пароль и логин в newtype) если надо - я конечно перепишу, я понимаю эту магию и какую дополнительную безопасность она дает, а по поводу имени  idD - возможно я ошибся, с этим - хотелось просто по короче;

**Comment by Sergey111991KV** [comment]
> Сокращать одну букву в имени не очень корректно.
> Например здесь: https://github.com/Sergey111991KV/thirdServer/blob/master/src/Domain/Services/LogMonad.hs#L38
> Функция, конечно, короткая и сокращение некритичное, но такие мелкие вещи сразу бросаются в глаза и ухудшают восприятие кода. Если функция была бы длиннее, то пришлось бы постоянно возвращаться к сигнатуре функции и смотреть, что такое `dat` по типу. `date` или `data`? Сокращения не должны вызывать сомнения.

блин я просмотрел, делал control-v + control-c  и не обратил внимания
