### ISSUE TITLE
Именование функций парсинга конфига

### ISSUE THREAD

**Issue by olegromashin** [Sergey111991KV/thirdServer#19]
Очень неговорящие имена:
myParser
mySeparator
По ним непонятно, что именно они парсят. myParser можно назвать как pairsParser или configParser. mySeparator -> eolParser.
Нужно стараться давать такие имена, по которым можно понять что делает функция не заглядывая в тело функции.

**Comment by Sergey111991KV** [comment]
Да я просто делал все с туториала по парсингу - там были эти названия, они и остались - думал больше чтобы подходило все в этот момент, а не об именах, но исправлюсь.
