### ISSUE TITLE
Бесполезная проверка

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/thirdServer#3]
Зачем нужна эта проверка? https://github.com/Sergey111991KV/thirdServer/blob/1e5ce87d0deca3311fc54b378fc728e3103b9f4f/src/Domain/Config/Config.hs#L35

Почему я не могу запустить со всеми дефолтными опциями?

**Comment by Sergey111991KV** [comment]
Удалил это, хотел добавить проверку вдруг человек не правильно ввел настройки, но... у меня то уже было fromMaybe

**Comment by ghost** [comment]
Переименуй `configVKwithPair`  еще плз, я понимаю ты просто скопипастил ее))

**Comment by Sergey111991KV** [comment]
С чего ты взял?)

**Comment by ghost** [comment]
Потому что там VK в названии и она была в боте))

**Comment by Sergey111991KV** [comment]
Ну ладно-ладно сдаюсь, Шерлок)
