### ISSUE TITLE
Не запускается сервер с ошибкой ErrorGetConfigtake

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/thirdServer#4]
```
$ stack exec thirdServer-exe
"ErrorGetConfigtake option for server"
```
файл server.options:
```
port 3000
postgres "host=localhost port=5432 dbname=db"
```

**Comment by Sergey111991KV** [comment]
Я скопировал парсер конфига с бота, а он не правильно парсил, и я вернул старый - а потом забыл про различие в системах и добавлении новой строки, щас должно работать
