### ISSUE TITLE
Hlint 

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/thirdServer#5]
```
$ hlint .
src/Lib.hs:1:1-28: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE QuasiQuotes #-}
Perhaps you should remove it.

src/Domain/Types/BusinessEntity/Category.hs:166:18-31: Suggestion: Use record patterns
Found:
  Category _ _ _
Perhaps:
  Category {}

2 hints
```

**Comment by Sergey111991KV** [comment]
Возможно я просто не на ту ветку скидывал это исправление - 
src/Lib.hs:1:1-28: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE QuasiQuotes #-}
Perhaps you should remove it. 
Это я тестил QuasiQuotes - конкатенация давала сбой, а начал заливать после уже на новую ветку(
src/Domain/Types/BusinessEntity/Category.hs:166:18-31: Suggestion: Use record patterns
Found:
  Category _ _ _
Perhaps:
  Category {} 
 а это почему то при сборке не выходит предупреждение, хотя в vc есть это предупреждение, если зайти в файл
Исправил
