### ISSUE TITLE
Французские кавычки в curl скриптах 

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/thirdServer#7]
В этих файлах:
- EditingCategory.sh
- EditingUser.sh
- EditingTag.sh
- EditingDraft.sh
- EditingAuthor.sh
- CreateUser.sh
- CreateTag.sh
- CreateDraft.sh
- CreateComment.sh
- CreateCategory.sh
- CreateAuthor.sh

заголовок `Content-Type` выставляется с помощью `«»` кавычек, которые для этого не предназначены:
`-H «Content-Type:application/json»`

**Comment by Sergey111991KV** [comment]
Поменял на  -H "Content-Type: application/json", но так как выставлено было не правильно и работало - думаю что и без этого параметрам можно было обойтись

**Comment by ghost** [comment]
Это твой сервер, и только ты можешь написать фильтрацию запросов по заголовкам))
