### ISSUE TITLE
Переписать функцию

### ISSUE THREAD

**Issue by ghost** [Sergey111991KV/thirdServer#8]
Функция 
https://github.com/Sergey111991KV/thirdServer/blob/1e5ce87d0deca3311fc54b378fc728e3103b9f4f/src/Domain/DomainEntityLogic/DomainEntityLogic.hs#L19
сейчас треснет от дублирующегося кода, требуя вынесения 
```
  either (\_ -> throwError ErrorConvert)
         (return . AnTag)
         (eitherDecode $ fromStrict b :: Either String Tag)
```
и параметризации его от `AnEntity` и типа сущности

**Comment by Sergey111991KV** [comment]
Спасибо большое! Я пока сам не смог это сделать - у меня все равно не так красиво получалось, как ты мне подсказал!

**Comment by ghost** [comment]
Если еще заморочится, то можно поменять аргументы ф-ии местами чтобы избавиться от b:
```
toAnEntity AuthorEntReq = decodeFromBytestring AnAuthor
toAnEntity UserEntReq = decodeFromBytestring AnUser
...
```
